// Mirrors frontend/src/modules/admin/constants.js ADMIN_PERMISSIONS. Keep the
// two lists in sync — this is what the backend validates staff permissions[]
// against and what requirePermission() checks tokens against.
const ADMIN_PERMISSIONS = Object.freeze([
  'admin.access',
  'admin.dashboard.view',
  'admin.analytics.view',
  'admin.catalog.view',
  'admin.catalog.manage',
  'admin.catalog.approve',
  'admin.catalog.products',
  'admin.catalog.categories',
  'admin.catalog.inventory',
  'admin.catalog.supplier_sync',
  'admin.dropship.view',
  'admin.dropship.manage',
  'admin.dropship.overview',
  'admin.dropship.partners',
  'admin.dropship.products',
  'admin.dropship.orders',
  'admin.dropship.supplier_sync',
  'admin.dropship.margins',
  'admin.orders.view',
  'admin.orders.manage',
  'admin.orders.cancel',
  'admin.orders.list',
  'admin.orders.sub_orders',
  'admin.orders.shipments',
  'admin.orders.invoices',
  'admin.returns.manage',
  'admin.people.view',
  'admin.people.manage',
  'admin.people.sellers',
  'admin.people.customers',
  'admin.people.support',
  'admin.kyc.review',
  'admin.roles.manage',
  'admin.users.manage',
  'admin.finance.view',
  'admin.finance.manage',
  'admin.finance.overview',
  'admin.finance.settlements',
  'admin.finance.rules',
  'admin.payout.prepare',
  'admin.payout.approve',
  'admin.accounting.view',
  'admin.accounting.post',
  'admin.tax.export',
  'admin.marketing.view',
  'admin.marketing.manage',
  'admin.marketing.coupons',
  'admin.marketing.banners',
  'admin.marketing.notifications',
  'admin.marketing.reviews',
  'admin.reports.view',
  'admin.settings.view',
  'admin.settings.manage',
  'admin.audit.view',
  'admin.system.manage',
]);

module.exports = { ADMIN_PERMISSIONS };
