// Mirrors frontend/src/modules/admin/constants.js ADMIN_PERMISSIONS. Keep the
// two lists in sync — this is what the backend validates staff permissions[]
// against and what requirePermission() checks tokens against.
const ADMIN_PERMISSIONS = Object.freeze([
  'admin.access',
  'admin.dashboard.view',
  'admin.analytics.view',
  'admin.catalog.view',
  'admin.catalog.manage',
  'admin.catalog.approve',
  'admin.catalog.products',
  'admin.catalog.categories',
  'admin.catalog.inventory',
  'admin.catalog.supplier_sync',
  'admin.dropship.view',
  'admin.dropship.manage',
  'admin.dropship.overview',
  'admin.dropship.partners',
  'admin.dropship.products',
  'admin.dropship.orders',
  'admin.dropship.supplier_sync',
  'admin.dropship.margins',
  // CJ Dropshipping module (Admin > CJ Dropshipping) — a distinct, provider-
  // specific surface from the generic admin.dropship.* partner module above.
  // Seller accounts must never hold any of these.
  'admin.cj.view',
  'admin.cj.settings',
  'admin.cj.catalogue',
  'admin.cj.products',
  'admin.cj.orders',
  'admin.cj.shipments',
  'admin.cj.returns',
  'admin.cj.refunds',
  'admin.cj.sync',
  'admin.orders.view',
  'admin.orders.manage',
  'admin.orders.cancel',
  'admin.orders.list',
  'admin.orders.sub_orders',
  'admin.orders.shipments',
  'admin.orders.invoices',
  'admin.returns.manage',
  'admin.people.view',
  'admin.people.manage',
  'admin.people.sellers',
  'admin.people.customers',
  'admin.people.support',
  'admin.kyc.review',
  'admin.roles.manage',
  'admin.users.manage',
  'admin.finance.view',
  'admin.finance.manage',
  'admin.finance.overview',
  'admin.finance.settlements',
  'admin.finance.rules',
  'admin.payout.prepare',
  'admin.payout.approve',
  'admin.accounting.view',
  'admin.accounting.post',
  // Accounting module (Admin > Accounting). One key per surface so a
  // read-only auditor, a settlements clerk and the person who actually
  // releases money are genuinely different roles — see
  // Router/adminAccountingRoutes.js for what each one gates.
  'admin.accounting.transactions.view',
  'admin.accounting.ledger.view',
  'admin.accounting.commission.view',
  'admin.accounting.commission.manage',
  'admin.accounting.settlement.view',
  'admin.accounting.settlement.manage',
  'admin.accounting.payout.view',
  'admin.accounting.payout.manage',
  'admin.accounting.refund.view',
  'admin.accounting.refund.manage',
  'admin.accounting.report.view',
  'admin.accounting.report.export',
  'admin.tax.export',
  'admin.marketing.view',
  'admin.marketing.manage',
  'admin.marketing.coupons',
  'admin.marketing.banners',
  'admin.marketing.notifications',
  'admin.marketing.reviews',
  'admin.reports.view',
  'admin.settings.view',
  'admin.settings.manage',
  'admin.audit.view',
  'admin.system.manage',
]);

module.exports = { ADMIN_PERMISSIONS };
