const SEED_BRANDS = [
  { name: 'boAt', logo: '/brands/boat.svg', isActive: true },
  { name: 'boAt Audio', logo: '/brands/boat.svg', isActive: true },
  { name: 'JBL', logo: '/brands/jbl.svg', isActive: true },
  { name: 'Sony', logo: '/brands/sony.svg', isActive: true },
  { name: 'Samsung', logo: '/brands/samsung.svg', isActive: true },
  { name: 'Apple', logo: '/brands/apple.svg', isActive: true },
  { name: 'OnePlus', logo: '/brands/oneplus.svg', isActive: true },
  { name: 'Xiaomi', logo: '/brands/xiaomi.svg', isActive: true },
  { name: 'Noise', logo: '/brands/noise.svg', isActive: true },
  { name: 'Noise Wearables', logo: '/brands/noise.svg', isActive: true },
  { name: 'Philips', logo: '/brands/philips.svg', isActive: true },
  { name: 'Philips Personal Care', logo: '/brands/philips.svg', isActive: true },
  { name: 'Prestige', logo: '/brands/prestige.svg', isActive: true },
  { name: 'Prestige Cookware', logo: '/brands/prestige.svg', isActive: true },
  { name: 'Pigeon', logo: '/brands/pigeon.svg', isActive: true },
  { name: 'Havells', logo: '/brands/havells.svg', isActive: true },
  { name: 'Nike', logo: '/brands/nike.svg', isActive: true },
  { name: 'Puma', logo: '/brands/puma.svg', isActive: true },
  { name: 'Adidas', logo: '/brands/adidas.svg', isActive: true },
  { name: "Levi's", logo: '/brands/levis.svg', isActive: true },
  { name: 'Roadster', logo: '/brands/roadster.svg', isActive: true },
  { name: 'HP', logo: '/brands/hp.svg', isActive: true },
  { name: 'Lenovo', logo: '/brands/lenovo.svg', isActive: true },
  { name: 'Logitech', logo: '/brands/logitech.svg', isActive: true },
  { name: 'Mamaearth', logo: '/brands/mamaearth.svg', isActive: true },
  { name: 'WOW Skin Science', logo: '/brands/wow.svg', isActive: true },
  { name: 'Krozenda Essentials', logo: '/brands/krozenda.svg', isActive: true },
];

module.exports = { SEED_BRANDS };
