const SEED_COUPONS = [
  {
    code: 'WELCOME10',
    description: 'Get 10% instant discount up to ₹500 on your first order.',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    maxDiscountAmount: 500,
    minOrderAmount: 999,
    usageLimit: 1000,
    usedCount: 142,
    perUserLimit: 1,
    applicableTo: 'ALL',
    customerEligibility: 'NEW',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
  },
  {
    code: 'SAVE200',
    description: 'Flat ₹200 off on all orders above ₹1,499.',
    discountType: 'FIXED',
    discountValue: 200,
    maxDiscountAmount: null,
    minOrderAmount: 1499,
    usageLimit: 500,
    usedCount: 88,
    perUserLimit: 2,
    applicableTo: 'ALL',
    customerEligibility: 'ALL',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
  },
  {
    code: 'FIRSTORDER',
    description: 'Special 15% discount for new shoppers on Krozenda.',
    discountType: 'PERCENTAGE',
    discountValue: 15,
    maxDiscountAmount: 300,
    minOrderAmount: 499,
    usageLimit: 2000,
    usedCount: 310,
    perUserLimit: 1,
    applicableTo: 'ALL',
    customerEligibility: 'NEW',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
  },
  {
    code: 'ELECTRO10',
    description: '10% discount up to ₹1,500 on all Electronics & Gadgets.',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    maxDiscountAmount: 1500,
    minOrderAmount: 2999,
    usageLimit: 300,
    usedCount: 65,
    perUserLimit: 1,
    applicableTo: 'CATEGORIES',
    categoryNames: ['Electronics & Gadgets'],
    customerEligibility: 'ALL',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
  },
  {
    code: 'FASHION15',
    description: 'Flat 15% off up to ₹600 on premium Fashion & Apparel.',
    discountType: 'PERCENTAGE',
    discountValue: 15,
    maxDiscountAmount: 600,
    minOrderAmount: 1199,
    usageLimit: 400,
    usedCount: 92,
    perUserLimit: 2,
    applicableTo: 'CATEGORIES',
    categoryNames: ['Fashion & Apparel'],
    customerEligibility: 'ALL',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
  },
  {
    code: 'FREESHIP',
    description: 'Flat ₹50 off shipping on any cart value over ₹499.',
    discountType: 'FIXED',
    discountValue: 50,
    maxDiscountAmount: null,
    minOrderAmount: 499,
    usageLimit: null,
    usedCount: 520,
    perUserLimit: null,
    applicableTo: 'ALL',
    customerEligibility: 'ALL',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
  },
  {
    code: 'MEGA50',
    description: '50% off up to ₹150 on essential everyday orders.',
    discountType: 'PERCENTAGE',
    discountValue: 50,
    maxDiscountAmount: 150,
    minOrderAmount: 299,
    usageLimit: 1000,
    usedCount: 420,
    perUserLimit: 1,
    applicableTo: 'ALL',
    customerEligibility: 'ALL',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
  },
  {
    code: 'EXPIRED20',
    description: 'Monsoon Kickoff Special 20% discount (Past campaign).',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    maxDiscountAmount: 400,
    minOrderAmount: 999,
    usageLimit: 200,
    usedCount: 200,
    perUserLimit: 1,
    applicableTo: 'ALL',
    customerEligibility: 'ALL',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-07-31'),
    isActive: true, // will be resolved as EXPIRED by status calculation
  },
];

module.exports = { SEED_COUPONS };
