const SEED_PRODUCTS = [
  // =========================================================================
  // 1. ELECTRONICS & GADGETS (12 Products)
  // =========================================================================
  {
    name: 'boAt Airdopes 141 Bluetooth Truly Wireless Earbuds',
    sku: 'BOAT-AIR-141',
    categoryName: 'Electronics & Gadgets',
    brandName: 'boAt',
    price: 4490,
    salePrice: 1299,
    discountPercent: 71,
    stock: 120,
    weight: 0.06,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Up to 42 hours total playtime, ENx noise-cancelling mics for crystal-clear calls, 8mm drivers with boAt Signature Sound, and IPX4 sweat resistance.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'boAt Rockerz 550 Over-Ear Wireless Headphones',
    sku: 'BOAT-ROC-550',
    categoryName: 'Electronics & Gadgets',
    brandName: 'boAt',
    price: 4999,
    salePrice: 1999,
    discountPercent: 60,
    stock: 75,
    weight: 0.24,
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Immerse in pure acoustic bliss with 50mm dynamic drivers, 20 hours battery backup, plush ear cushions, and dual wireless/AUX connectivity.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'boAt Stone 650 10W Portable Bluetooth Speaker',
    sku: 'BOAT-STO-650',
    categoryName: 'Electronics & Gadgets',
    brandName: 'boAt',
    price: 3990,
    salePrice: 1599,
    discountPercent: 60,
    stock: 45,
    weight: 0.65,
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Rugged diamond-cut design with IPX5 water resistance, powerful 10W subwoofer sound, and up to 7 hours of uninterrupted playtime.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'JBL Flip 6 Portable Waterproof Bluetooth Speaker',
    sku: 'JBL-FLIP-6',
    categoryName: 'Electronics & Gadgets',
    brandName: 'JBL',
    price: 13999,
    salePrice: 9999,
    discountPercent: 29,
    stock: 30,
    weight: 0.55,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
    ],
    description: '2-way speaker system delivering loud, crystal-clear, powerful sound with deep bass. IP67 waterproof and dustproof with 12 hours playback.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'JBL Tune 760NC Active Noise Cancelling Headphones',
    sku: 'JBL-T760NC',
    categoryName: 'Electronics & Gadgets',
    brandName: 'JBL',
    price: 7999,
    salePrice: 5499,
    discountPercent: 31,
    stock: 25,
    weight: 0.22,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Active Noise Cancelling headphone with JBL Pure Bass Sound, 35 hours battery life with BT+NC, multi-point connection, and hands-free calling.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Sony WH-1000XM5 Wireless Industry-Leading Noise Canceling Headphones',
    sku: 'SONY-WH-XM5',
    categoryName: 'Electronics & Gadgets',
    brandName: 'Sony',
    price: 34990,
    salePrice: 26990,
    discountPercent: 23,
    stock: 15,
    weight: 0.25,
    images: [
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Two processors and 8 microphones for unprecedented noise cancellation. Auto NC Optimizer, 30 hours battery, ultra-comfortable lightweight design.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Sony WF-C500 Truly Wireless Bluetooth Earbuds',
    sku: 'SONY-WF-C500',
    categoryName: 'Electronics & Gadgets',
    brandName: 'Sony',
    price: 8990,
    salePrice: 4490,
    discountPercent: 50,
    stock: 40,
    weight: 0.04,
    images: [
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Ergonomic surface design for snug fit, DSEE restores high frequency sounds, 20 hours battery with case, IPX4 splash rating.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Noise ColorFit Pulse 2 Max 1.85-inch Smartwatch',
    sku: 'NOISE-PULSE-2M',
    categoryName: 'Electronics & Gadgets',
    brandName: 'Noise',
    price: 4999,
    salePrice: 1499,
    discountPercent: 70,
    stock: 150,
    weight: 0.05,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Massive 1.85" TFT LCD with 550 nits brightness, Bluetooth calling with Tru Sync, 100 sports modes, and 10 days battery life.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Noise Diva Diamond-Cut AMOLED Smartwatch for Women',
    sku: 'NOISE-DIVA-GLD',
    categoryName: 'Electronics & Gadgets',
    brandName: 'Noise',
    price: 6999,
    salePrice: 2999,
    discountPercent: 57,
    stock: 35,
    weight: 0.04,
    images: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Diamond cut dial with metallic strap, 1.1" AMOLED display with Always On Display, female health tracking, and AI voice assistance.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Philips TAB4218 120W Bluetooth Soundbar with Subwoofer',
    sku: 'PHI-TAB-4218',
    categoryName: 'Electronics & Gadgets',
    brandName: 'Philips',
    price: 12990,
    salePrice: 6999,
    discountPercent: 46,
    stock: 20,
    weight: 4.2,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
    ],
    description: '2.1 CH wired subwoofer with 120W peak output, HDMI ARC, optical input, Bluetooth 5.0, and sleek wall-mountable geometric profile.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'boAt Wave Call 2 Smartwatch with HD Bluetooth Calling',
    sku: 'BOAT-WAVE-2',
    categoryName: 'Electronics & Gadgets',
    brandName: 'boAt',
    price: 6990,
    salePrice: 1699,
    discountPercent: 76,
    stock: 80,
    weight: 0.05,
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    ],
    description: '1.83" HD display with responsive dialpad, Crest OS+ health ecosystem, 700+ active modes, and customized watch face studio.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'boAt Bassheads 242 in-Ear Wired Sports Earphones',
    sku: 'BOAT-BASS-242',
    categoryName: 'Electronics & Gadgets',
    brandName: 'boAt',
    price: 1490,
    salePrice: 499,
    discountPercent: 66,
    stock: 200,
    weight: 0.02,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Secure ear hooks for gym and running, IPX4 water and sweat resistance, 10mm dynamic bass drivers, and tangle-free braided cable.',
    isActive: false, // inactive sample for admin catalog test
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 2. MOBILES & ACCESSORIES (10 Products)
  // =========================================================================
  {
    name: 'Samsung Galaxy S23 5G (Phantom Black, 128GB)',
    sku: 'SAM-S23-128',
    categoryName: 'Mobiles & Accessories',
    brandName: 'Samsung',
    price: 74999,
    salePrice: 49999,
    discountPercent: 33,
    stock: 25,
    weight: 0.17,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Snapdragon 8 Gen 2 for Galaxy, 50MP pro-grade camera with Nightography, Dynamic AMOLED 2X 120Hz display, and armor aluminum frame.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Apple iPhone 14 (Blue, 128GB Storage)',
    sku: 'APL-IPH14-128',
    categoryName: 'Mobiles & Accessories',
    brandName: 'Apple',
    price: 69900,
    salePrice: 59999,
    discountPercent: 14,
    stock: 30,
    weight: 0.17,
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
    ],
    description: '6.1-inch Super Retina XDR display, advanced dual camera system with Photonic Engine, Crash Detection, and all-day battery life.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'OnePlus 11R 5G (Sonic Black, 16GB RAM, 256GB Storage)',
    sku: 'OP-11R-256',
    categoryName: 'Mobiles & Accessories',
    brandName: 'OnePlus',
    price: 44999,
    salePrice: 37999,
    discountPercent: 16,
    stock: 40,
    weight: 0.2,
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Snapdragon 8+ Gen 1 chipset, 100W SUPERVOOC charging (1-100% in 25 mins), 50MP Sony IMX890 sensor with OIS, and 120Hz Super Fluid AMOLED.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Xiaomi 13 Pro 5G (Ceramic Black, 256GB)',
    sku: 'MI-13PRO-256',
    categoryName: 'Mobiles & Accessories',
    brandName: 'Xiaomi',
    price: 89999,
    salePrice: 74999,
    discountPercent: 17,
    stock: 12,
    weight: 0.23,
    images: [
      'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Co-engineered with Leica: 1-inch Sony IMX989 sensor, 120W HyperCharge, Snapdragon 8 Gen 2, 2K 120Hz E6 AMOLED curved display.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Samsung Galaxy M34 5G (Midnight Blue, 6GB RAM, 128GB)',
    sku: 'SAM-M34-128',
    categoryName: 'Mobiles & Accessories',
    brandName: 'Samsung',
    price: 24499,
    salePrice: 16499,
    discountPercent: 33,
    stock: 60,
    weight: 0.21,
    images: [
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Monster 6000mAh battery, 50MP No Shake Cam with OIS, 120Hz FHD+ Super AMOLED display, and 4 generations of OS upgrades guaranteed.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Redmi Note 12 5G (Matte Black, 128GB)',
    sku: 'MI-RN12-128',
    categoryName: 'Mobiles & Accessories',
    brandName: 'Xiaomi',
    price: 19999,
    salePrice: 14999,
    discountPercent: 25,
    stock: 50,
    weight: 0.19,
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'SuperNote experience with 120Hz Super AMOLED display, Snapdragon 4 Gen 1 5G, 48MP AI triple camera, and 33W fast charging.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Apple 20W USB-C Original Fast Power Adapter',
    sku: 'APL-20W-ADP',
    categoryName: 'Mobiles & Accessories',
    brandName: 'Apple',
    price: 1900,
    salePrice: 1599,
    discountPercent: 16,
    stock: 90,
    weight: 0.08,
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1601593346740-925612772716?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Fast, efficient charging at home or on the go. Compatible with any USB-C enabled device, optimized for iPhone 12/13/14/15 series.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'boAt 20000mAh 22.5W Fast Charging Power Bank',
    sku: 'BOAT-PB-20K',
    categoryName: 'Mobiles & Accessories',
    brandName: 'boAt',
    price: 3499,
    salePrice: 1699,
    discountPercent: 51,
    stock: 65,
    weight: 0.42,
    images: [
      'https://images.unsplash.com/photo-1609592424360-154b679d67ba?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Dual input Type-C & Micro-USB, 22.5W Two-Way fast charging, 12-layer smart IC circuit protection, and metallic aluminum matte finish.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'OnePlus SUPERVOOC 80W Fast Power Adapter',
    sku: 'OP-80W-ADP',
    categoryName: 'Mobiles & Accessories',
    brandName: 'OnePlus',
    price: 3299,
    salePrice: 2499,
    discountPercent: 24,
    stock: 40,
    weight: 0.12,
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1609592424360-154b679d67ba?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Super-speed charging with advanced GaN technology, multi-protection system for overheating and voltage surge, backward compatible.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda Ultra Armor Shockproof Hybrid Phone Case',
    sku: 'KRZ-CS-UNIV',
    categoryName: 'Mobiles & Accessories',
    brandName: 'Krozenda Essentials',
    price: 999,
    salePrice: 349,
    discountPercent: 65,
    stock: 140,
    weight: 0.04,
    images: [
      'https://images.unsplash.com/photo-1601593346740-925612772716?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Military grade drop tested protection, anti-yellowing crystal clear acrylic back, raised camera lip, and tactile responsive buttons.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 3. COMPUTERS & PERIPHERALS (8 Products)
  // =========================================================================
  {
    name: 'HP Pavilion 15 (AMD Ryzen 5, 16GB RAM, 512GB SSD)',
    sku: 'HP-PAV-15',
    categoryName: 'Computers & Peripherals',
    brandName: 'HP',
    price: 64999,
    salePrice: 52990,
    discountPercent: 18,
    stock: 20,
    weight: 1.75,
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    ],
    description: '15.6-inch FHD anti-glare micro-edge display, AMD Ryzen 5 5625U 6-core processor, Audio by B&O, fast charge, and Windows 11 Home.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Lenovo IdeaPad Slim 3 12th Gen Intel Core i5',
    sku: 'LEN-IP3-I5',
    categoryName: 'Computers & Peripherals',
    brandName: 'Lenovo',
    price: 68990,
    salePrice: 48990,
    discountPercent: 29,
    stock: 18,
    weight: 1.63,
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Thin and light laptop with Intel Core i5-1235U, 16GB DDR4 RAM, 512GB NVMe SSD, Dolby Audio, and privacy shutter HD camera.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Apple MacBook Air M2 Chip (13.6-inch Liquid Retina, 256GB)',
    sku: 'APL-MBA-M2',
    categoryName: 'Computers & Peripherals',
    brandName: 'Apple',
    price: 114900,
    salePrice: 94990,
    discountPercent: 17,
    stock: 10,
    weight: 1.24,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Strikingly thin design in Starlight aluminum, lightning-fast 8-core CPU and up to 10-core GPU, 18-hour battery, MagSafe charging.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Logitech MX Master 3S Advanced Wireless Mouse',
    sku: 'LOGI-MXM-3S',
    categoryName: 'Computers & Peripherals',
    brandName: 'Logitech',
    price: 10995,
    salePrice: 8495,
    discountPercent: 23,
    stock: 35,
    weight: 0.14,
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Quiet clicks with 90% less noise, 8K DPI any-surface tracking including glass, MagSpeed electromagnetic scrolling, and USB-C quick charge.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Logitech K380 Multi-Device Bluetooth Wireless Keyboard',
    sku: 'LOGI-K380-GR',
    categoryName: 'Computers & Peripherals',
    brandName: 'Logitech',
    price: 3195,
    salePrice: 2495,
    discountPercent: 22,
    stock: 50,
    weight: 0.42,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Connect up to 3 devices simultaneously with Easy-Switch button. Minimalist compact layout with comfortable scooped low-profile keys.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'HP 200 Wireless Optical Mouse with 2.4GHz Dongle',
    sku: 'HP-M200-WL',
    categoryName: 'Computers & Peripherals',
    brandName: 'HP',
    price: 999,
    salePrice: 499,
    discountPercent: 50,
    stock: 120,
    weight: 0.08,
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Contoured ambidextrous shape designed for all-day comfort. Precise optical sensor with 1000 DPI and up to 12 months battery life.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Lenovo 23.8-inch FHD IPS NearEdgeless Monitor',
    sku: 'LEN-MON-24',
    categoryName: 'Computers & Peripherals',
    brandName: 'Lenovo',
    price: 14500,
    salePrice: 8999,
    discountPercent: 38,
    stock: 22,
    weight: 3.4,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Full HD 1920x1080 IPS panel with 75Hz refresh rate and AMD FreeSync. Ultra-slim 3-side NearEdgeless bezels with eye care certification.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Logitech C922 Pro Stream Full HD 1080p Webcam',
    sku: 'LOGI-C922-PRO',
    categoryName: 'Computers & Peripherals',
    brandName: 'Logitech',
    price: 13995,
    salePrice: 9495,
    discountPercent: 32,
    stock: 15,
    weight: 0.16,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Designed for serious streamers: Hyper-fast 1080p at 30fps or 720p at 60fps streaming, dual omnidirectional stereo mics, and auto light correction.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 4. FASHION & APPAREL (12 Products)
  // =========================================================================
  {
    name: "Levi's Men's 511 Slim Fit Stretch Denim Jeans",
    sku: 'LEV-511-DNM',
    categoryName: 'Fashion & Apparel',
    brandName: "Levi's",
    price: 3999,
    salePrice: 2199,
    discountPercent: 45,
    stock: 55,
    weight: 0.6,
    images: [
      'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Modern slim fit with room to move. Crafted with premium stretch denim and Levi’s Flex technology for maximum mobility and comfort.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: "Levi's Classic Housemark Pure Cotton Graphic T-Shirt",
    sku: 'LEV-TSH-HM',
    categoryName: 'Fashion & Apparel',
    brandName: "Levi's",
    price: 1499,
    salePrice: 799,
    discountPercent: 47,
    stock: 80,
    weight: 0.18,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Standard fit crewneck crafted from 100% breathable combed cotton with the iconic Levi’s batwing logo screenprint on the chest.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Puma Men Cotton Blend Athletic Jogger Track Pants',
    sku: 'PUM-JOG-BLK',
    categoryName: 'Fashion & Apparel',
    brandName: 'Puma',
    price: 2499,
    salePrice: 1299,
    discountPercent: 48,
    stock: 65,
    weight: 0.45,
    images: [
      'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'French terry fleece fabric with elasticated waistband, external drawcord, side pockets, and ribbed cuffs for athletic everyday styling.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Puma Training DryCELL Moisture Wicking Gym T-Shirt',
    sku: 'PUM-DRY-TSH',
    categoryName: 'Fashion & Apparel',
    brandName: 'Puma',
    price: 1799,
    salePrice: 899,
    discountPercent: 50,
    stock: 90,
    weight: 0.15,
    images: [
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'dryCELL performance technology designed to wick moisture from the body and keep you free of sweat during workouts.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Roadster Men Solid Washed Rugged Denim Jacket',
    sku: 'RDS-JKT-DNM',
    categoryName: 'Fashion & Apparel',
    brandName: 'Roadster',
    price: 3499,
    salePrice: 1499,
    discountPercent: 57,
    stock: 40,
    weight: 0.8,
    images: [
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Sturdy 100% cotton denim trucker jacket with button placket, button flap chest pockets, and washed vintage highway aesthetic.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Roadster Men Pure Cotton Tartan Checked Casual Shirt',
    sku: 'RDS-SHT-CHK',
    categoryName: 'Fashion & Apparel',
    brandName: 'Roadster',
    price: 1999,
    salePrice: 699,
    discountPercent: 65,
    stock: 110,
    weight: 0.22,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Regular fit pre-washed cotton casual shirt with spread collar, curved hemline, and classic button cuff details.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Adidas Originals Trefoil Heavyweight Fleece Hoodie',
    sku: 'ADI-TRE-HD',
    categoryName: 'Fashion & Apparel',
    brandName: 'Adidas',
    price: 5999,
    salePrice: 3599,
    discountPercent: 40,
    stock: 35,
    weight: 0.7,
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Cozy heavyweight French terry hoodie celebrating authentic Adidas heritage with an oversized Trefoil logo print and kangaroo pocket.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Adidas Aeroready 3-Stripes Lightweight Training Shorts',
    sku: 'ADI-SHR-3S',
    categoryName: 'Fashion & Apparel',
    brandName: 'Adidas',
    price: 2299,
    salePrice: 1299,
    discountPercent: 43,
    stock: 70,
    weight: 0.18,
    images: [
      'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Moisture-absorbing AEROREADY construction with elastic drawcord waist and iconic 3-stripes along the sides for training or leisure.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Nike Sportswear Club Fleece Crewneck Sweatshirt',
    sku: 'NKE-CLB-CRW',
    categoryName: 'Fashion & Apparel',
    brandName: 'Nike',
    price: 3795,
    salePrice: 2495,
    discountPercent: 34,
    stock: 45,
    weight: 0.5,
    images: [
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Brushed-back fleece is soft and smooth against the skin. Standard fit for a relaxed, easy feel with embroidered Nike Futura logo.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Nike Dri-FIT Legend Short-Sleeve Athletic Training Top',
    sku: 'NKE-LEG-TOP',
    categoryName: 'Fashion & Apparel',
    brandName: 'Nike',
    price: 1995,
    salePrice: 1295,
    discountPercent: 35,
    stock: 85,
    weight: 0.14,
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Dri-FIT technology moves sweat away from your skin for quicker evaporation, helping you stay dry and comfortable through intense sets.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Roadster Women High-Rise Clean Look Ankle-Length Mom Jeans',
    sku: 'RDS-WMN-MOM',
    categoryName: 'Fashion & Apparel',
    brandName: 'Roadster',
    price: 2499,
    salePrice: 999,
    discountPercent: 60,
    stock: 50,
    weight: 0.55,
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Vintage high-waist fit with slightly tapered ankle profile, 5-pocket styling, and comfortable breathable cotton denim blend.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: "Levi's Men Sherpa Lined Corduroy Winter Trucker Jacket",
    sku: 'LEV-SHP-JKT',
    categoryName: 'Fashion & Apparel',
    brandName: "Levi's",
    price: 7999,
    salePrice: 4799,
    discountPercent: 40,
    stock: 20,
    weight: 1.1,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Original cold-weather trucker silhouette with fuzzy sherpa insulation on body and collar, and quilted lining in sleeves.',
    isActive: false, // inactive sample for admin catalog test
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 5. FOOTWEAR & SNEAKERS (10 Products)
  // =========================================================================
  {
    name: "Nike Air Max SC Men's Retro Leather Running Sneakers",
    sku: 'NKE-AM-SC',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Nike',
    price: 6995,
    salePrice: 4495,
    discountPercent: 36,
    stock: 45,
    weight: 0.75,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Heritage track vibes with visible Max Air cushioning. Leather, textile and mesh combine for a durable construction that breathes.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: "Nike Revolution 6 Next Nature Men's Road Running Shoes",
    sku: 'NKE-REV-6',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Nike',
    price: 3995,
    salePrice: 2695,
    discountPercent: 33,
    stock: 60,
    weight: 0.65,
    images: [
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Plush mesh upper along the collar provides a comfortable feel. Foam midsole delivers a softer ride than the Revolution 5.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Puma Smash V2 Unisex Leather Casual Court Sneakers',
    sku: 'PUM-SMH-V2',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Puma',
    price: 3999,
    salePrice: 1999,
    discountPercent: 50,
    stock: 80,
    weight: 0.7,
    images: [
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Tennis-inspired classic updated with smooth leather upper, SoftFoam+ comfort sockliner for instant step-in cushioning, and durable rubber outsole.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Puma Deviate Nitro 2 Carbon Plate Elite Marathon Shoes',
    sku: 'PUM-NIT-2',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Puma',
    price: 15999,
    salePrice: 10999,
    discountPercent: 31,
    stock: 15,
    weight: 0.52,
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'NITRO Elite foam for pinnacle responsiveness, reworked INNOPLATE carbon composite propulsion, and PUMAGRIP all-weather traction.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Adidas Ultraboost Light Running Shoes with Boost Cushioning',
    sku: 'ADI-UB-LGT',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Adidas',
    price: 18999,
    salePrice: 12999,
    discountPercent: 32,
    stock: 20,
    weight: 0.58,
    images: [
      'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Experience epic energy return with the lightest Boost ever made. Linear Energy Point system integrated on the outsole for extra spring.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Adidas Grand Court Base 2.0 Classic Tennis Sneakers',
    sku: 'ADI-GC-2',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Adidas',
    price: 4999,
    salePrice: 2499,
    discountPercent: 50,
    stock: 75,
    weight: 0.68,
    images: [
      'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=800&auto=format&fit=crop&q=80',
    ],
    description: '70s style court silhouette reinvented for today with soft Cloudfoam Comfort sockliner, synthetic leather upper, and stitched 3-stripes.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Nike Court Vision Low Casual Streetwear Sneakers',
    sku: 'NKE-CV-LOW',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Nike',
    price: 5495,
    salePrice: 3795,
    discountPercent: 31,
    stock: 50,
    weight: 0.72,
    images: [
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'In love with the classic look of 80s basketball, meet the Court Vision Low. Stitched overlays, padded collar, and vulcanized rubber sole.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Puma SOFTRIDE Fly Lightweight Walking Shoes',
    sku: 'PUM-SR-FLY',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Puma',
    price: 3499,
    salePrice: 1699,
    discountPercent: 51,
    stock: 90,
    weight: 0.5,
    images: [
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Built with SOFTRIDE midsole foam for extreme cushioning and all-day comfort. Easy slip-on bootie construction with dynamic lacing.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Adidas Adilette Comfort Slides with Contoured Footbed',
    sku: 'ADI-ADL-SLD',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Adidas',
    price: 2799,
    salePrice: 1599,
    discountPercent: 43,
    stock: 100,
    weight: 0.35,
    images: [
      'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Slide into pure relaxation with pillowy Cloudfoam Plus contoured footbed and classic single-bandage synthetic bandage upper.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Roadster Men High-Top Streetwear Canvas Sneakers',
    sku: 'RDS-CNV-HI',
    categoryName: 'Footwear & Sneakers',
    brandName: 'Roadster',
    price: 2199,
    salePrice: 899,
    discountPercent: 59,
    stock: 65,
    weight: 0.65,
    images: [
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Rugged canvas high-top with contrast rubber toe cap, metal eyelets, cushioned ankle collar, and vulcanized textured outsole.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 6. BEAUTY & PERSONAL CARE (10 Products)
  // =========================================================================
  {
    name: 'Mamaearth Onion Hair Fall Control Oil with Redensyl (150ml)',
    sku: 'MAM-ONN-OIL',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Mamaearth',
    price: 419,
    salePrice: 349,
    discountPercent: 17,
    stock: 150,
    weight: 0.2,
    images: [
      'https://images.unsplash.com/photo-1608248597359-52e04313f8c8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Reduces hair fall, accelerates hair growth, and strengthens follicles. Powered by Sulfur, Potassium and Redensyl. Dermatologically tested.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Mamaearth Vitamin C Daily Glow Face Wash with Turmeric (100ml)',
    sku: 'MAM-VITC-FW',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Mamaearth',
    price: 259,
    salePrice: 199,
    discountPercent: 23,
    stock: 180,
    weight: 0.12,
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1567928815116-2c9b6cb6cb77?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Brightens skin tone, cleanses deeply without drying, and promotes even skin complexion. Sulfate-free, paraben-free and cruelty-free.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Mamaearth Ubtan Natural Face Scrub with Walnut & Saffron (100g)',
    sku: 'MAM-UBT-SCB',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Mamaearth',
    price: 349,
    salePrice: 289,
    discountPercent: 17,
    stock: 95,
    weight: 0.13,
    images: [
      'https://images.unsplash.com/photo-1567928815116-2c9b6cb6cb77?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608248597359-52e04313f8c8?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Exfoliates dead cells, removes sun tan, and clears skin impurities. Walnut beads gently scrub while saffron imparts a warm golden glow.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'WOW Skin Science Apple Cider Vinegar Shampoo (300ml)',
    sku: 'WOW-ACV-SHM',
    categoryName: 'Beauty & Personal Care',
    brandName: 'WOW Skin Science',
    price: 499,
    salePrice: 329,
    discountPercent: 34,
    stock: 120,
    weight: 0.35,
    images: [
      'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Raw Himalayan apple cider vinegar, sweet almond oil, and argan oil to detoxify scalp, clear buildup, and restore silkiness and shine.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'WOW Skin Science 20% Vitamin C Concentrated Face Serum (30ml)',
    sku: 'WOW-VITC-SRM',
    categoryName: 'Beauty & Personal Care',
    brandName: 'WOW Skin Science',
    price: 699,
    salePrice: 449,
    discountPercent: 36,
    stock: 85,
    weight: 0.09,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Ferulic acid and hyaluronic acid formula to fight pigmentation, boost collagen synthesis, and protect skin against atmospheric damage.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'WOW Skin Science Brightening Vitamin C Body Wash (250ml)',
    sku: 'WOW-BW-VITC',
    categoryName: 'Beauty & Personal Care',
    brandName: 'WOW Skin Science',
    price: 399,
    salePrice: 249,
    discountPercent: 38,
    stock: 110,
    weight: 0.3,
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Invigorating citrus scent with mulberry and liquorice extracts that soften dry skin, gently cleanse, and brighten everyday shower routine.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Philips Series 3000 All-in-One Trimmer with 9 Attachments',
    sku: 'PHI-TRM-3000',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Philips',
    price: 2195,
    salePrice: 1549,
    discountPercent: 29,
    stock: 60,
    weight: 0.3,
    images: [
      'https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1559591937-e10c7104b281?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Self-sharpening stainless steel blades that never need oiling. 60 minutes cordless use, nose and ear hair trimmer attachment included.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Philips SilkProtect Keratin Ceramic Hair Straightener',
    sku: 'PHI-STR-KER',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Philips',
    price: 2495,
    salePrice: 1899,
    discountPercent: 24,
    stock: 40,
    weight: 0.45,
    images: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'SilkProtect technology for optimized heat damage prevention. Keratin-infused ceramic plates heat up in 60 seconds with 210°C professional heat.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Philips Sonicare 1100 Rechargeable Electric Toothbrush',
    sku: 'PHI-SNC-1100',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Philips',
    price: 2999,
    salePrice: 1999,
    discountPercent: 33,
    stock: 35,
    weight: 0.25,
    images: [
      'https://images.unsplash.com/photo-1559591937-e10c7104b281?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Removes up to 3x more plaque than manual toothbrushes. QuadPacer and SmarTimer encourage 2-minute brushing, 14-day battery life per charge.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Mamaearth Tea Tree Oil-Free Face Moisturizer (80g)',
    sku: 'MAM-TT-MST',
    categoryName: 'Beauty & Personal Care',
    brandName: 'Mamaearth',
    price: 319,
    salePrice: 269,
    discountPercent: 16,
    stock: 75,
    weight: 0.1,
    images: [
      'https://images.unsplash.com/photo-1617897903246-719242758050?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Tea tree and salicylic acid formula prevents acne breakouts, hydrates without oiliness, and restores skin barrier elasticity.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 7. HOME & LIVING (8 Products)
  // =========================================================================
  {
    name: 'Krozenda Microfiber Double Bed Comforter All-Season Quilt',
    sku: 'KRZ-CMF-DBL',
    categoryName: 'Home & Living',
    brandName: 'Krozenda Essentials',
    price: 2999,
    salePrice: 1399,
    discountPercent: 53,
    stock: 50,
    weight: 1.8,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Reversible dual tone 200 GSM hypoallergenic microfiber fill. Diamond baffle stitching prevents filling from shifting and clumping.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Krozenda 100% Pure Combed Cotton 300 TC King Bedsheet',
    sku: 'KRZ-SHT-KNG',
    categoryName: 'Home & Living',
    brandName: 'Krozenda Essentials',
    price: 2499,
    salePrice: 1099,
    discountPercent: 56,
    stock: 70,
    weight: 1.1,
    images: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Sateen weave king size bedsheet (108x108 inches) with 2 matching pillow covers. Color-fast dyes and breathable luxury soft texture.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Havells Glaze 18W Square LED Recessed Ceiling Light',
    sku: 'HAV-LED-18W',
    categoryName: 'Home & Living',
    brandName: 'Havells',
    price: 1150,
    salePrice: 649,
    discountPercent: 44,
    stock: 120,
    weight: 0.35,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1550985616-10810253b84d?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Ultra-slim design with high lumen efficacy (100 lm/W). Wide beam angle for uniform light spread and surge protection up to 4kV.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Havells Freshia AP-40 HEPA Filter Smart Air Purifier',
    sku: 'HAV-AP-40',
    categoryName: 'Home & Living',
    brandName: 'Havells',
    price: 16990,
    salePrice: 10490,
    discountPercent: 38,
    stock: 12,
    weight: 6.5,
    images: [
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'True HEPA filter captures 99.97% of dust and allergens down to 0.3 microns. Clean Air Delivery Rate (CADR) 350 m³/hr with real-time PM2.5 display.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Philips Deco Prime 9W Smart WiFi Tunable LED Bulb (B22)',
    sku: 'PHI-BLB-9W',
    categoryName: 'Home & Living',
    brandName: 'Philips',
    price: 899,
    salePrice: 499,
    discountPercent: 45,
    stock: 140,
    weight: 0.09,
    images: [
      'https://images.unsplash.com/photo-1550985616-10810253b84d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Control your lighting with WiZ app or voice via Alexa and Google Assistant. 16 million colors, tunable warm to cool white, no hub required.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Krozenda Slow Rebound Orthopedic Memory Foam Pillow',
    sku: 'KRZ-PLW-MEM',
    categoryName: 'Home & Living',
    brandName: 'Krozenda Essentials',
    price: 1999,
    salePrice: 849,
    discountPercent: 58,
    stock: 60,
    weight: 0.95,
    images: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Contoured cervical support designed to relieve neck and shoulder pain. Removable, machine-washable breathable bamboo fiber zippered cover.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Havells Stealth Air 1200mm Dust Resistant Ceiling Fan',
    sku: 'HAV-FAN-STL',
    categoryName: 'Home & Living',
    brandName: 'Havells',
    price: 5490,
    salePrice: 3890,
    discountPercent: 29,
    stock: 25,
    weight: 4.8,
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Aerodynamic twin-canopy blades for silent operation and highest air delivery (280 m³/min). Hydrophobic nano-coating keeps blades dust-free.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda 3-Layer Blackout Room Darkening Window Curtains (Set of 2)',
    sku: 'KRZ-CRT-BLK',
    categoryName: 'Home & Living',
    brandName: 'Krozenda Essentials',
    price: 2199,
    salePrice: 899,
    discountPercent: 59,
    stock: 45,
    weight: 1.4,
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Blocks 99% sunlight and harmful UV rays. Thermal insulation reduces outside noise and maintains room temperature with silver rust-proof eyelets.',
    isActive: false, // inactive sample
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 8. KITCHEN & APPLIANCES (8 Products)
  // =========================================================================
  {
    name: 'Prestige Svachh Hard Anodized 3L Pressure Cooker',
    sku: 'PRS-CKR-3L',
    categoryName: 'Kitchen & Appliances',
    brandName: 'Prestige',
    price: 2490,
    salePrice: 1690,
    discountPercent: 32,
    stock: 70,
    weight: 1.6,
    images: [
      'https://images.unsplash.com/photo-1584990347449-389f4170668b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Deep lid design controls froth spillage onto the cooker body. Induction and gas stove compatible base with durable stay-cool ergonomic handle.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Prestige Iris 750 Watt Mixer Grinder with 3 Stainless Steel Jars',
    sku: 'PRS-MXG-750',
    categoryName: 'Kitchen & Appliances',
    brandName: 'Prestige',
    price: 4995,
    salePrice: 2899,
    discountPercent: 42,
    stock: 45,
    weight: 4.5,
    images: [
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584990347449-389f4170668b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Heavy-duty 750W motor with overload protector, multi-utility stainless steel blades, and transparent juicer jar with sieve attachment.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Prestige Omega Deluxe Granite 3-Piece Non-Stick Cookware Set',
    sku: 'PRS-OMG-SET',
    categoryName: 'Kitchen & Appliances',
    brandName: 'Prestige',
    price: 3890,
    salePrice: 2390,
    discountPercent: 39,
    stock: 35,
    weight: 2.8,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584990347449-389f4170668b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Includes fry pan, omni tawa, and kadai with glass lid. 5-layer German granite non-stick coating, metal spoon friendly, dishwasher safe.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Pigeon by Stovekraft 1.5L Stainless Steel Electric Kettle',
    sku: 'PGN-KTL-15L',
    categoryName: 'Kitchen & Appliances',
    brandName: 'Pigeon',
    price: 1195,
    salePrice: 599,
    discountPercent: 50,
    stock: 160,
    weight: 0.85,
    images: [
      'https://images.unsplash.com/photo-1594213114663-ddf4f240f08d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Rapid 1500W boil element with automatic cut-off and dry-boil protection. 360-degree cordless pirouette base for right or left-hand use.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Pigeon Cruise 1800-Watt Digital Induction Cooktop',
    sku: 'PGN-IND-1800',
    categoryName: 'Kitchen & Appliances',
    brandName: 'Pigeon',
    price: 3195,
    salePrice: 1549,
    discountPercent: 52,
    stock: 65,
    weight: 1.9,
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1594213114663-ddf4f240f08d?w=800&auto=format&fit=crop&q=80',
    ],
    description: '7-segment LED display for power and temperature, 93% energy saving technology, preset Indian cooking menus, and high-grade crystal glass plate.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Pigeon Handy Quick Vegetable & Dry Fruit Chopper with 3 Blades',
    sku: 'PGN-CHP-400',
    categoryName: 'Kitchen & Appliances',
    brandName: 'Pigeon',
    price: 495,
    salePrice: 219,
    discountPercent: 56,
    stock: 220,
    weight: 0.25,
    images: [
      'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584990347449-389f4170668b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Easy string pull mechanism chops onions, ginger, and vegetables in seconds. Unbreakable BPA-free plastic container with food-grade steel blades.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Philips Digital Air Fryer HD9252 with Rapid Air Technology',
    sku: 'PHI-AFR-9252',
    categoryName: 'Kitchen & Appliances',
    brandName: 'Philips',
    price: 11995,
    salePrice: 7999,
    discountPercent: 33,
    stock: 25,
    weight: 4.8,
    images: [
      'https://images.unsplash.com/photo-1584990347449-389f4170668b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Fry with up to 90% less fat. Starfish bottom design circulates hot air evenly. 7 preset touch screen cooking modes and NutriU recipe app integration.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Havells Aqua Plus 1.2L Double Wall Stainless Steel Kettle',
    sku: 'HAV-KTL-12L',
    categoryName: 'Kitchen & Appliances',
    brandName: 'Havells',
    price: 2490,
    salePrice: 1399,
    discountPercent: 44,
    stock: 50,
    weight: 1.05,
    images: [
      'https://images.unsplash.com/photo-1594213114663-ddf4f240f08d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Cool touch outer plastic body with seamless 304 food-grade stainless steel interior. Auto shut-off on boiling and wide mouth for effortless cleaning.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 9. FITNESS & OUTDOORS (8 Products)
  // =========================================================================
  {
    name: 'Nike Hypercharge 24oz Chug Spill-Proof Water Bottle',
    sku: 'NKE-BTL-24Z',
    categoryName: 'Fitness & Outdoors',
    brandName: 'Nike',
    price: 1995,
    salePrice: 1395,
    discountPercent: 30,
    stock: 65,
    weight: 0.22,
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Durable impact-resistant construction with quick-twist slider cap for fast hydration on the move. Ergonomic handle attaches easily to gym bags.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Puma Training Gym Duffel Bag with Shoe Compartment (35L)',
    sku: 'PUM-DFL-35L',
    categoryName: 'Fitness & Outdoors',
    brandName: 'Puma',
    price: 2799,
    salePrice: 1399,
    discountPercent: 50,
    stock: 55,
    weight: 0.48,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Spacious main compartment with two-way zip, ventilated side pocket for shoes or damp gear, and padded adjustable shoulder strap.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Adidas Adjustable Speed Skipping Jump Rope with Steel Ball Bearings',
    sku: 'ADI-SKP-ROP',
    categoryName: 'Fitness & Outdoors',
    brandName: 'Adidas',
    price: 1499,
    salePrice: 799,
    discountPercent: 47,
    stock: 120,
    weight: 0.2,
    images: [
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Smooth 360-degree rotation ball bearing mechanism for fast, tangle-free skipping. Easily adjustable 300cm coated steel cable with grip handles.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda Eco-Friendly Non-Slip TPE Exercise Yoga Mat (6mm)',
    sku: 'KRZ-YGA-MAT',
    categoryName: 'Fitness & Outdoors',
    brandName: 'Krozenda Essentials',
    price: 1999,
    salePrice: 799,
    discountPercent: 60,
    stock: 90,
    weight: 0.85,
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Double-sided textured surface ensures optimum grip on wood, tile or concrete. High density 6mm cushioning protects joints, carrying strap included.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Krozenda Rubber Encased Hex Dumbbell Pair (10kg)',
    sku: 'KRZ-DMB-10K',
    categoryName: 'Fitness & Outdoors',
    brandName: 'Krozenda Essentials',
    price: 3499,
    salePrice: 1999,
    discountPercent: 43,
    stock: 30,
    weight: 10.0,
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Solid cast iron core with heavy-duty rubber coating protects floors and reduces impact noise. Ergonomic chrome knurled grip prevents slippage.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Noise Fit Force Rugged Outdoor GPS Bluetooth Calling Watch',
    sku: 'NOISE-FRC-RGD',
    categoryName: 'Fitness & Outdoors',
    brandName: 'Noise',
    price: 5999,
    salePrice: 2499,
    discountPercent: 58,
    stock: 40,
    weight: 0.06,
    images: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Military certified shock, dust and temperature resistance. In-built compass, altimeter, barometric sensor, and multi-GNSS satellite tracking.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda Heavy Resistance Bands Set of 5 with Door Anchor',
    sku: 'KRZ-RST-SET',
    categoryName: 'Fitness & Outdoors',
    brandName: 'Krozenda Essentials',
    price: 1499,
    salePrice: 599,
    discountPercent: 60,
    stock: 110,
    weight: 0.4,
    images: [
      'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    ],
    description: '100% natural latex tube bands with color-coded resistance from 10 lbs to 50 lbs. Includes foam handles, ankle straps, and workout manual.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Puma Unisex Lightweight Breathable Performance Running Cap',
    sku: 'PUM-RUN-CAP',
    categoryName: 'Fitness & Outdoors',
    brandName: 'Puma',
    price: 1199,
    salePrice: 699,
    discountPercent: 42,
    stock: 80,
    weight: 0.08,
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Laser cut ventilation panels for airflow, moisture-wicking interior sweatband, reflective Puma cat logo for nighttime visibility.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 10. GROCERY & ESSENTIALS (8 Products)
  // =========================================================================
  {
    name: 'Krozenda Organic 100% Cold-Pressed Extra Virgin Coconut Oil (500ml)',
    sku: 'KRZ-COCO-500',
    categoryName: 'Grocery & Essentials',
    brandName: 'Krozenda Essentials',
    price: 499,
    salePrice: 299,
    discountPercent: 40,
    stock: 130,
    weight: 0.55,
    images: [
      'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Extracted from fresh raw coconut milk without heat processing. Rich in Lauric acid, zero preservatives, ideal for raw cooking and hair conditioning.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Krozenda Raw Himalayan Wild Forest Honey Unpasteurized (500g)',
    sku: 'KRZ-HNY-500',
    categoryName: 'Grocery & Essentials',
    brandName: 'Krozenda Essentials',
    price: 650,
    salePrice: 425,
    discountPercent: 35,
    stock: 100,
    weight: 0.65,
    images: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Collected by native beekeepers from pristine Himalayan flora. Unheated, unfiltered, preserving active natural enzymes and pollen.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Krozenda Premium California Whole Raw Almonds Badam (500g)',
    sku: 'KRZ-ALM-500',
    categoryName: 'Grocery & Essentials',
    brandName: 'Krozenda Essentials',
    price: 799,
    salePrice: 499,
    discountPercent: 38,
    stock: 140,
    weight: 0.52,
    images: [
      'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    ],
    description: '100% natural, crisp and crunchy California almonds. Packed with Vitamin E, protein and heart-healthy dietary fiber in zip-lock food pouch.',
    isActive: true,
    isFlashsale: true,
    isTrending: true,
  },
  {
    name: 'Krozenda Roasted & Salted Goa Jumbo Cashews Kaju (250g)',
    sku: 'KRZ-CSH-250',
    categoryName: 'Grocery & Essentials',
    brandName: 'Krozenda Essentials',
    price: 550,
    salePrice: 349,
    discountPercent: 37,
    stock: 90,
    weight: 0.28,
    images: [
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'W240 grade jumbo whole cashews slowly slow-roasted and lightly sprinkled with pink rock salt. Perfect healthy snack.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda Organic Raw Chia Seeds Superfood for Weight Loss (250g)',
    sku: 'KRZ-CHIA-250',
    categoryName: 'Grocery & Essentials',
    brandName: 'Krozenda Essentials',
    price: 399,
    salePrice: 199,
    discountPercent: 50,
    stock: 160,
    weight: 0.27,
    images: [
      'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Powerhouse of plant-based Omega-3, calcium, and antioxidants. Expand in liquid to keep you full and improve digestive health.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda 100% Pure Kashmiri Mongra Saffron Kesar (1g)',
    sku: 'KRZ-SFR-1G',
    categoryName: 'Grocery & Essentials',
    brandName: 'Krozenda Essentials',
    price: 699,
    salePrice: 449,
    discountPercent: 36,
    stock: 75,
    weight: 0.02,
    images: [
      'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Grade A1 all-red stigma threads sourced directly from the fields of Pampore, Kashmir. Intensely aromatic with deep red coloring power.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Krozenda Whole Aromatic Green Cardamom Chhoti Elaichi (100g)',
    sku: 'KRZ-ELC-100',
    categoryName: 'Grocery & Essentials',
    brandName: 'Krozenda Essentials',
    price: 499,
    salePrice: 329,
    discountPercent: 34,
    stock: 110,
    weight: 0.12,
    images: [
      'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Hand-picked plump 8mm green pods from Idukki, Kerala. Essential spice for tea, biryani, and traditional desserts.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda 100% Wholegrain Gluten-Free Rolled Oats (1kg)',
    sku: 'KRZ-OAT-1KG',
    categoryName: 'Grocery & Essentials',
    brandName: 'Krozenda Essentials',
    price: 349,
    salePrice: 219,
    discountPercent: 37,
    stock: 150,
    weight: 1.05,
    images: [
      'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'High in Beta-Glucan soluble fiber that helps manage cholesterol and supports sustained morning energy with zero added sugars.',
    isActive: false, // inactive sample
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 11. TOYS & GAMES (4 Products)
  // =========================================================================
  {
    name: 'Krozenda Educational Natural Wooden Building Blocks Set (100 Pieces)',
    sku: 'KRZ-TOY-BLK',
    categoryName: 'Toys & Games',
    brandName: 'Krozenda Essentials',
    price: 1499,
    salePrice: 799,
    discountPercent: 47,
    stock: 60,
    weight: 1.4,
    images: [
      'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Non-toxic water-based paints on solid pine wood. Encourages spatial reasoning, motor skills, and creative architectural construction for kids 3+.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Krozenda High-Speed 1:18 Off-Road Remote Control Monster Truck',
    sku: 'KRZ-RC-TRK',
    categoryName: 'Toys & Games',
    brandName: 'Krozenda Essentials',
    price: 2999,
    salePrice: 1599,
    discountPercent: 47,
    stock: 45,
    weight: 0.9,
    images: [
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
    ],
    description: '2.4GHz anti-interference radio control, 4WD independent suspension springs, rugged all-terrain rubber tires, and dual rechargeable battery packs.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Krozenda Classic Wooden Magnetic Folding Chess & Checkers Board 12x12',
    sku: 'KRZ-CHS-MAG',
    categoryName: 'Toys & Games',
    brandName: 'Krozenda Essentials',
    price: 1999,
    salePrice: 999,
    discountPercent: 50,
    stock: 70,
    weight: 0.8,
    images: [
      'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Handcrafted Sheesham wood pieces with felt bottom and embedded magnets. Foldable travel design with interior velvet compartments for storage.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda 1000-Piece Ancient World Map Jigsaw Puzzle',
    sku: 'KRZ-PZL-1000',
    categoryName: 'Toys & Games',
    brandName: 'Krozenda Essentials',
    price: 1299,
    salePrice: 599,
    discountPercent: 54,
    stock: 80,
    weight: 0.75,
    images: [
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'High precision cut pieces made from recycled thick blueboard that snap together seamlessly. Full color bonus poster included for reference.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },

  // =========================================================================
  // 12. AUTOMOTIVE ACCESSORIES (4 Products)
  // =========================================================================
  {
    name: 'Krozenda 60W Dual Port Fast Car Charger (PD 30W + QC 3.0)',
    sku: 'KRZ-AUTO-CHG',
    categoryName: 'Automotive Accessories',
    brandName: 'Krozenda Essentials',
    price: 1199,
    salePrice: 499,
    discountPercent: 58,
    stock: 140,
    weight: 0.05,
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'All-metal aluminum body with soft blue ring LED indicator. Supports simultaneous high-speed charging for iPhones, Samsungs, and tablets.',
    isActive: true,
    isFlashsale: true,
    isTrending: false,
  },
  {
    name: 'Krozenda Magnetic Air Vent & Dashboard Universal Car Phone Mount',
    sku: 'KRZ-MNT-MAG',
    categoryName: 'Automotive Accessories',
    brandName: 'Krozenda Essentials',
    price: 999,
    salePrice: 399,
    discountPercent: 60,
    stock: 110,
    weight: 0.12,
    images: [
      'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    ],
    description: '6 powerful N52 neodymium magnets hold phone rock-solid even over speed breakers. 360-degree ball joint allows landscape and portrait rotation.',
    isActive: true,
    isFlashsale: false,
    isTrending: true,
  },
  {
    name: 'Krozenda High Power 120W Portable Handheld Wet & Dry Car Vacuum Cleaner',
    sku: 'KRZ-VAC-CAR',
    categoryName: 'Automotive Accessories',
    brandName: 'Krozenda Essentials',
    price: 2499,
    salePrice: 1199,
    discountPercent: 52,
    stock: 50,
    weight: 0.95,
    images: [
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    ],
    description: '6000PA strong cyclonic suction cleans pet hair, crumbs and spilled drinks. Washable HEPA filter with 4.5m power cord for 12V cigarette lighter.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
  {
    name: 'Krozenda Smart Digital Tire Pressure Gauge with Backlit LCD (150 PSI)',
    sku: 'KRZ-TPG-150',
    categoryName: 'Automotive Accessories',
    brandName: 'Krozenda Essentials',
    price: 1499,
    salePrice: 699,
    discountPercent: 53,
    stock: 80,
    weight: 0.14,
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Lighted nozzle and display screen for visibility in dimly lit areas. 4 measurement settings: PSI, BAR, KPA, and Kg/cm² with auto shut-off.',
    isActive: true,
    isFlashsale: false,
    isTrending: false,
  },
];

module.exports = { SEED_PRODUCTS };
