const SEED_USERS = [
  {
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    mobileNumber: '9876543210',
    password: 'Customer@123',
    gender: 'male',
    dob: new Date('1994-06-15'),
    walletBalance: 1500,
    role: 'customer',
    isActive: true,
  },
  {
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    mobileNumber: '9876543211',
    password: 'Customer@123',
    gender: 'female',
    dob: new Date('1996-09-22'),
    walletBalance: 750,
    role: 'customer',
    isActive: true,
  },
  {
    name: 'Rohan Verma',
    email: 'rohan.verma@example.com',
    mobileNumber: '9876543212',
    password: 'Customer@123',
    gender: 'male',
    dob: new Date('1991-03-10'),
    walletBalance: 3200,
    role: 'customer',
    isActive: true,
  },
  {
    name: 'Ananya Iyer',
    email: 'ananya.iyer@example.com',
    mobileNumber: '9876543213',
    password: 'Customer@123',
    gender: 'female',
    dob: new Date('1998-11-05'),
    walletBalance: 0,
    role: 'customer',
    isActive: true,
  },
  {
    name: 'Vikram Malhotra',
    email: 'vikram.malhotra@example.com',
    mobileNumber: '9876543214',
    password: 'Customer@123',
    gender: 'male',
    dob: new Date('1988-07-30'),
    walletBalance: 500,
    role: 'customer',
    isActive: true,
  },
  {
    name: 'Neha Gupta',
    email: 'neha.gupta@example.com',
    mobileNumber: '9876543215',
    password: 'Customer@123',
    gender: 'female',
    dob: new Date('1995-01-18'),
    walletBalance: 1200,
    role: 'customer',
    isActive: true,
  },
  {
    name: 'Aditya Joshi',
    email: 'aditya.joshi@example.com',
    mobileNumber: '9876543216',
    password: 'Customer@123',
    gender: 'male',
    dob: new Date('1993-12-08'),
    walletBalance: 0,
    role: 'customer',
    isActive: true,
  },
  {
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    mobileNumber: '9876543217',
    password: 'Customer@123',
    gender: 'female',
    dob: new Date('1997-04-25'),
    walletBalance: 0,
    role: 'customer',
    isActive: false, // Inactive user for testing admin user-status filters
  },
];

const SEED_ADDRESSES = [
  // Aarav Sharma
  {
    userEmail: 'aarav.sharma@example.com',
    type: 'home',
    fullName: 'Aarav Sharma',
    phone: '9876543210',
    line1: 'Flat 402, Sea Green Apartments, Worli Sea Face',
    line2: 'Opposite Worli Sports Club',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400030',
    country: 'India',
    isDefault: true,
  },
  {
    userEmail: 'aarav.sharma@example.com',
    type: 'office',
    fullName: 'Aarav Sharma (Work)',
    phone: '9876543210',
    line1: 'Tower B, 7th Floor, Godrej BKC, G Block',
    line2: 'Bandra Kurla Complex',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    country: 'India',
    isDefault: false,
  },

  // Priya Patel
  {
    userEmail: 'priya.patel@example.com',
    type: 'home',
    fullName: 'Priya Patel',
    phone: '9876543211',
    line1: 'B-12, Shivalik Villa, Judges Bungalow Road',
    line2: 'Bodakdev',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380054',
    country: 'India',
    isDefault: true,
  },
  {
    userEmail: 'priya.patel@example.com',
    type: 'office',
    fullName: 'Priya Patel',
    phone: '9876543211',
    line1: '304, Iscon Elegance, S.G. Highway',
    line2: 'Prahlad Nagar Cross Road',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380015',
    country: 'India',
    isDefault: false,
  },

  // Rohan Verma
  {
    userEmail: 'rohan.verma@example.com',
    type: 'home',
    fullName: 'Rohan Verma',
    phone: '9876543212',
    line1: 'House No 124, 4th Cross, 6th Block',
    line2: 'Koramangala',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560095',
    country: 'India',
    isDefault: true,
  },
  {
    userEmail: 'rohan.verma@example.com',
    type: 'other',
    fullName: 'Rohan Verma (Parental Home)',
    phone: '9876543212',
    line1: 'Villa 8, Palm Meadows, HAL 2nd Stage',
    line2: 'Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    country: 'India',
    isDefault: false,
  },

  // Ananya Iyer
  {
    userEmail: 'ananya.iyer@example.com',
    type: 'home',
    fullName: 'Ananya Iyer',
    phone: '9876543213',
    line1: '14, 2nd Main Road, Kasturibai Nagar',
    line2: 'Near Adyar Bus Depot',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600020',
    country: 'India',
    isDefault: true,
  },

  // Vikram Malhotra
  {
    userEmail: 'vikram.malhotra@example.com',
    type: 'home',
    fullName: 'Vikram Malhotra',
    phone: '9876543214',
    line1: 'C-28, Ground Floor, Hauz Khas Enclave',
    line2: 'Near Deer Park Gate 2',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110016',
    country: 'India',
    isDefault: true,
  },
  {
    userEmail: 'vikram.malhotra@example.com',
    type: 'office',
    fullName: 'Vikram Malhotra',
    phone: '9876543214',
    line1: 'Statesman House, Barakhamba Road',
    line2: 'Connaught Place',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110001',
    country: 'India',
    isDefault: false,
  },

  // Neha Gupta
  {
    userEmail: 'neha.gupta@example.com',
    type: 'home',
    fullName: 'Neha Gupta',
    phone: '9876543215',
    line1: 'Penthouse 1201, Marvel Bounty, Magarpatta Road',
    line2: 'Hadapsar',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411028',
    country: 'India',
    isDefault: true,
  },

  // Aditya Joshi
  {
    userEmail: 'aditya.joshi@example.com',
    type: 'home',
    fullName: 'Aditya Joshi',
    phone: '9876543216',
    line1: 'Flat 804, My Home Bhooja, Gachibowli',
    line2: 'Hitec City Knowledge Park',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    country: 'India',
    isDefault: true,
  },
  {
    userEmail: 'aditya.joshi@example.com',
    type: 'office',
    fullName: 'Aditya Joshi',
    phone: '9876543216',
    line1: 'Building 12B, Mindspace IT Park',
    line2: 'Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    country: 'India',
    isDefault: false,
  },
];

module.exports = { SEED_USERS, SEED_ADDRESSES };
