const SEED_VENDORS = [
  {
    vendorType: 'B2C',
    name: 'Urban Cart Retail Pvt Ltd',
    email: 'contact@urbancart.in',
    mobile: '9820112233',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Electronics & Gadgets',
    gstRegistered: true,
    business: {
      businessName: 'Urban Cart Retail Private Limited',
      tradeName: 'Urban Cart',
      businessType: 'private_limited',
      pan: 'AAACU1234F',
      gstin: '27AAACU1234F1Z5',
      udyamNumber: 'UDYAM-MH-03-0012345',
    },
    contactPerson: {
      name: 'Rajesh Singhania',
      designation: 'Managing Director',
      mobile: '9820112233',
      email: 'rajesh@urbancart.in',
    },
    address: {
      addressLine: 'Unit 402, Trade Link Tower, Lower Parel',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400013',
      country: 'India',
    },
    bank: {
      accountHolderName: 'Urban Cart Retail Pvt Ltd',
      bankName: 'HDFC Bank',
      accountNumber: '50200012345678',
      ifsc: 'HDFC0000123',
    },
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    vendorType: 'B2B',
    name: 'TechNest India Solutions LLP',
    email: 'sales@technestindia.com',
    mobile: '9880223344',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Computers & Peripherals',
    gstRegistered: true,
    business: {
      businessName: 'TechNest India Solutions LLP',
      tradeName: 'TechNest Supply',
      businessType: 'llp',
      pan: 'AABCT5678G',
      gstin: '29AABCT5678G1Z2',
      udyamNumber: 'UDYAM-KR-03-0054321',
    },
    contactPerson: {
      name: 'Karthik Ramanathan',
      designation: 'Partner & Supply Chain Lead',
      mobile: '9880223344',
      email: 'karthik@technestindia.com',
    },
    address: {
      addressLine: 'Plot 18, Electronic City Phase 1',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560100',
      country: 'India',
    },
    bank: {
      accountHolderName: 'TechNest India Solutions LLP',
      bankName: 'ICICI Bank',
      accountNumber: '000205012345',
      ifsc: 'ICIC0000002',
    },
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    vendorType: 'B2C',
    name: 'Style Avenue Apparels',
    email: 'info@styleavenue.co.in',
    mobile: '9825334455',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Fashion & Apparel',
    gstRegistered: true,
    business: {
      businessName: 'Style Avenue Apparels Partnership Firm',
      tradeName: 'Style Avenue',
      businessType: 'partnership',
      pan: 'AABFS9012H',
      gstin: '24AABFS9012H1Z8',
      udyamNumber: 'UDYAM-GJ-01-0098765',
    },
    contactPerson: {
      name: 'Manish Choksi',
      designation: 'Partner',
      mobile: '9825334455',
      email: 'manish@styleavenue.co.in',
    },
    address: {
      addressLine: 'Ring Road Textile Market, Ring Road',
      city: 'Surat',
      state: 'Gujarat',
      pincode: '395002',
      country: 'India',
    },
    bank: {
      accountHolderName: 'Style Avenue Apparels',
      bankName: 'State Bank of India',
      accountNumber: '31234567890',
      ifsc: 'SBIN0001234',
    },
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    vendorType: 'B2C',
    name: 'HomeCraft Living Studio',
    email: 'support@homecraftliving.in',
    mobile: '9829445566',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Home & Living',
    gstRegistered: true,
    business: {
      businessName: 'HomeCraft Handicrafts & Furnishings',
      tradeName: 'HomeCraft Living',
      businessType: 'proprietorship',
      pan: 'ABCPH3456J',
      gstin: '08ABCPH3456J1Z1',
      udyamNumber: 'UDYAM-RJ-17-0034567',
    },
    contactPerson: {
      name: 'Pooja Agarwal',
      designation: 'Founder & Proprietor',
      mobile: '9829445566',
      email: 'pooja@homecraftliving.in',
    },
    address: {
      addressLine: 'S-14, Industrial Area, Mansarovar',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302020',
      country: 'India',
    },
    bank: {
      accountHolderName: 'HomeCraft Living Studio',
      bankName: 'Axis Bank',
      accountNumber: '912010012345678',
      ifsc: 'UTIB0000123',
    },
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    vendorType: 'B2C',
    name: 'Daily Needs Consumer Hub',
    email: 'orders@dailyneedshub.com',
    mobile: '9811556677',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Grocery & Essentials',
    gstRegistered: true,
    business: {
      businessName: 'Daily Needs Consumer Hub Private Limited',
      tradeName: 'Daily Needs Hub',
      businessType: 'private_limited',
      pan: 'AACCD7890K',
      gstin: '07AACCD7890K1Z4',
      udyamNumber: 'UDYAM-DL-08-0065432',
    },
    contactPerson: {
      name: 'Sanjay Kapoor',
      designation: 'Operations Head',
      mobile: '9811556677',
      email: 'sanjay@dailyneedshub.com',
    },
    address: {
      addressLine: 'Plot 42, Okhla Industrial Area Phase 3',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110020',
      country: 'India',
    },
    bank: {
      accountHolderName: 'Daily Needs Consumer Hub Pvt Ltd',
      bankName: 'Kotak Mahindra Bank',
      accountNumber: '2511234567',
      ifsc: 'KKBK0000123',
    },
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    vendorType: 'B2C',
    name: 'Apex Mobile World',
    email: 'connect@apexmobile.in',
    mobile: '9848667788',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Mobiles & Accessories',
    gstRegistered: true,
    business: {
      businessName: 'Apex Mobile Communications',
      tradeName: 'Apex Mobile World',
      businessType: 'proprietorship',
      pan: 'ABCDE1122L',
      gstin: '36ABCDE1122L1Z9',
      udyamNumber: 'UDYAM-TS-09-0043210',
    },
    contactPerson: {
      name: 'Venkat Reddy',
      designation: 'General Manager',
      mobile: '9848667788',
      email: 'venkat@apexmobile.in',
    },
    address: {
      addressLine: 'Shop 12, Chenoy Trade Centre, Parklane',
      city: 'Secunderabad',
      state: 'Telangana',
      pincode: '500003',
      country: 'India',
    },
    bank: {
      accountHolderName: 'Apex Mobile World',
      bankName: 'HDFC Bank',
      accountNumber: '50100098765432',
      ifsc: 'HDFC0000456',
    },
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    vendorType: 'B2C',
    name: 'FitPulse Athletics',
    email: 'info@fitpulse.co.in',
    mobile: '9822778899',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Fitness & Outdoors',
    gstRegistered: true,
    business: {
      businessName: 'FitPulse Sporting Goods India',
      tradeName: 'FitPulse Athletics',
      businessType: 'partnership',
      pan: 'AABCF3344M',
      gstin: '27AABCF3344M1Z7',
      udyamNumber: 'UDYAM-MH-26-0087654',
    },
    contactPerson: {
      name: 'Abhishek Kulkarni',
      designation: 'Partner',
      mobile: '9822778899',
      email: 'abhishek@fitpulse.co.in',
    },
    address: {
      addressLine: 'F-8, MIDC Industrial Area, Chakan',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '410501',
      country: 'India',
    },
    bank: {
      accountHolderName: 'FitPulse Athletics',
      bankName: 'Bank of Baroda',
      accountNumber: '04510200001234',
      ifsc: 'BARB0CHAKAN',
    },
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    vendorType: 'B2C',
    name: 'SoleVibe Footwear Co',
    email: 'sales@solevibe.in',
    mobile: '9837889900',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Footwear & Sneakers',
    gstRegistered: true,
    business: {
      businessName: 'SoleVibe Shoe Manufacturing Company',
      tradeName: 'SoleVibe',
      businessType: 'proprietorship',
      pan: 'ABCDE5566N',
      gstin: '09ABCDE5566N1Z3',
      udyamNumber: 'UDYAM-UP-01-0023456',
    },
    contactPerson: {
      name: 'Deepak Sharma',
      designation: 'Proprietor',
      mobile: '9837889900',
      email: 'deepak@solevibe.in',
    },
    address: {
      addressLine: 'Site B, Sikandra Industrial Area',
      city: 'Agra',
      state: 'Uttar Pradesh',
      pincode: '282007',
      country: 'India',
    },
    bank: {
      accountHolderName: 'SoleVibe Footwear Co',
      bankName: 'Punjab National Bank',
      accountNumber: '1234002100012345',
      ifsc: 'PUNB0123400',
    },
    verificationStatus: 'APPROVED',
    isActive: true,
  },
  {
    vendorType: 'B2C',
    name: 'PureBliss Wellness & Beauty',
    email: 'contact@pureblissbeauty.com',
    mobile: '9830990011',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Beauty & Personal Care',
    gstRegistered: true,
    business: {
      businessName: 'PureBliss Organic Cosmeceuticals',
      tradeName: 'PureBliss Beauty',
      businessType: 'proprietorship',
      pan: 'ABCPB7788P',
      gstin: '19ABCPB7788P1Z6',
      udyamNumber: 'UDYAM-WB-10-0019283',
    },
    contactPerson: {
      name: 'Sharmistha Roy',
      designation: 'Product Specialist',
      mobile: '9830990011',
      email: 'sharmistha@pureblissbeauty.com',
    },
    address: {
      addressLine: '22A, Park Street, Block C',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700016',
      country: 'India',
    },
    bank: {
      accountHolderName: 'PureBliss Wellness & Beauty',
      bankName: 'Federal Bank',
      accountNumber: '11223344556677',
      ifsc: 'FDRL0001234',
    },
    verificationStatus: 'PENDING',
    isActive: false,
  },
  {
    vendorType: 'B2B',
    name: 'AutoGear Pro Dynamics',
    email: 'wholesale@autogearpro.in',
    mobile: '9840001122',
    password: 'Vendor@123',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    categoryName: 'Automotive Accessories',
    gstRegistered: true,
    business: {
      businessName: 'AutoGear Pro Dynamics India Pvt Ltd',
      tradeName: 'AutoGear Pro',
      businessType: 'private_limited',
      pan: 'AACCA9900Q',
      gstin: '33AACCA9900Q1Z0',
      udyamNumber: 'UDYAM-TN-02-0076543',
    },
    contactPerson: {
      name: 'R. Senthil Kumar',
      designation: 'Commercial Director',
      mobile: '9840001122',
      email: 'senthil@autogearpro.in',
    },
    address: {
      addressLine: 'Plot 7B, Ambattur Industrial Estate',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600058',
      country: 'India',
    },
    bank: {
      accountHolderName: 'AutoGear Pro Dynamics Pvt Ltd',
      bankName: 'Canara Bank',
      accountNumber: '0234101001234',
      ifsc: 'CNRB0000234',
    },
    verificationStatus: 'UNDER_REVIEW',
    isActive: false,
  },
];

module.exports = { SEED_VENDORS };
