// Semantic name -> react-icons mapping. Nothing outside this file should
// import from 'react-icons/*' directly — call <Icon name="..." /> instead,
// so swapping icon sets later is a one-file change.
//
// One family only (Feather). Mixing families is the fastest way to make an
// admin panel look assembled rather than designed.

import {
  FiActivity,
  FiAlertCircle,
  FiAlertTriangle,
  FiArchive,
  FiArrowDown,
  FiArrowLeft,
  FiArrowRight,
  FiArrowUp,
  FiBarChart2,
  FiBell,
  FiBookOpen,
  FiBookmark,
  FiBox,
  FiBriefcase,
  FiCalendar,
  FiCheck,
  FiCheckCircle,
  FiCheckSquare,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiChevronsLeft,
  FiChevronsRight,
  FiClock,
  FiColumns,
  FiCopy,
  FiCreditCard,
  FiDatabase,
  FiDollarSign,
  FiDownload,
  FiEdit2,
  FiExternalLink,
  FiEye,
  FiEyeOff,
  FiFile,
  FiFileText,
  FiFilter,
  FiFlag,
  FiFolder,
  FiGrid,
  FiHelpCircle,
  FiHome,
  FiImage,
  FiInfo,
  FiKey,
  FiLayout,
  FiLifeBuoy,
  FiLink,
  FiList,
  FiLock,
  FiLogOut,
  FiMail,
  FiMapPin,
  FiMaximize2,
  FiMenu,
  FiMinimize2,
  FiMinus,
  FiMoreHorizontal,
  FiMoreVertical,
  FiMove,
  FiPackage,
  FiPaperclip,
  FiPercent,
  FiPhone,
  FiPieChart,
  FiPlus,
  FiPrinter,
  FiRefreshCw,
  FiRotateCcw,
  FiSave,
  FiSearch,
  FiSend,
  FiServer,
  FiSettings,
  FiShield,
  FiShoppingBag,
  FiSliders,
  FiStar,
  FiTag,
  FiTrash2,
  FiTrendingDown,
  FiTrendingUp,
  FiTruck,
  FiUpload,
  FiUser,
  FiUserCheck,
  FiUsers,
  FiX,
  FiXCircle,
  FiZap,
  FiMessageCircle,
  FiPauseCircle,
  FiPlayCircle,
  FiShoppingCart,
} from 'react-icons/fi'

const ICONS = Object.freeze({
  // ---- navigation ------------------------------------------------------
  dashboard: FiHome,
  analytics: FiBarChart2,
  products: FiPackage,
  categories: FiGrid,
  brands: FiBookmark,
  inventory: FiBox,
  approvals: FiCheckCircle,
  dropshipping: FiTruck,
  orders: FiShoppingBag,
  shipments: FiTruck,
  returns: FiRotateCcw,
  invoices: FiFileText,
  sellers: FiBriefcase,
  customers: FiUsers,
  kyc: FiUserCheck,
  finance: FiTrendingUp,
  accounting: FiDollarSign,
  settlements: FiCreditCard,
  ledger: FiBookOpen,
  tax: FiPercent,
  reports: FiPieChart,
  marketing: FiTag,
  coupons: FiTag,
  store: FiShoppingBag,
  banners: FiImage,
  cms: FiLayout,
  campaigns: FiSend,
  reviews: FiStar,
  staff: FiUser,
  roles: FiShield,
  settings: FiSettings,
  audit: FiClock,
  backups: FiDatabase,
  integrations: FiServer,
  support: FiLifeBuoy,
  notifications: FiBell,
  catalog: FiPackage,
  truck: FiTruck,
  eye: FiEye,
  shield: FiShield,
  star: FiStar,

  // ---- actions ---------------------------------------------------------
  search: FiSearch,
  add: FiPlus,
  remove: FiMinus,
  edit: FiEdit2,
  delete: FiTrash2,
  close: FiX,
  check: FiCheck,
  upload: FiUpload,
  download: FiDownload,
  print: FiPrinter,
  copy: FiCopy,
  link: FiLink,
  externalLink: FiExternalLink,
  filter: FiFilter,
  columns: FiColumns,
  sliders: FiSliders,
  refresh: FiRefreshCw,
  save: FiSave,
  send: FiSend,
  show: FiEye,
  hide: FiEyeOff,
  lock: FiLock,
  key: FiKey,
  drag: FiMove,
  expand: FiMaximize2,
  collapse: FiMinimize2,
  logout: FiLogOut,
  attach: FiPaperclip,

  // ---- direction -------------------------------------------------------
  chevronUp: FiChevronUp,
  chevronDown: FiChevronDown,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  chevronsLeft: FiChevronsLeft,
  chevronsRight: FiChevronsRight,
  arrowUp: FiArrowUp,
  arrowDown: FiArrowDown,
  arrowLeft: FiArrowLeft,
  arrowRight: FiArrowRight,
  menu: FiMenu,
  more: FiMoreVertical,
  moreHorizontal: FiMoreHorizontal,

  // ---- status & feedback ----------------------------------------------
  success: FiCheck,
  successCircle: FiCheckCircle,
  warning: FiAlertTriangle,
  danger: FiAlertCircle,
  error: FiXCircle,
  info: FiInfo,
  help: FiHelpCircle,
  pending: FiClock,
  flag: FiFlag,
  activity: FiActivity,
  live: FiZap,
  trendUp: FiTrendingUp,
  trendDown: FiTrendingDown,

  // ---- objects ---------------------------------------------------------
  calendar: FiCalendar,
  file: FiFile,
  folder: FiFolder,
  archive: FiArchive,
  list: FiList,
  checkbox: FiCheckSquare,
  money: FiDollarSign,
  mail: FiMail,
  phone: FiPhone,
  location: FiMapPin,
  user: FiUser,
  users: FiUsers,
  pause: FiPauseCircle,
  play: FiPlayCircle,
  message: FiMessageCircle,
  cart: FiShoppingCart,
  percent: FiPercent,
})

export const ICON_NAMES = Object.freeze(Object.keys(ICONS))

export function Icon({ name, className = 'h-4 w-4', ...props }) {
  const Component = ICONS[name]

  if (!Component) {
    if (import.meta.env.DEV) {
      console.warn(`[Icon] Unknown icon name: "${name}". Add it to ICONS in components/ui/Icon.jsx.`)
    }
    return null
  }

  return <Component className={className} aria-hidden="true" focusable="false" {...props} />
}
